# Generated by Django 6.0.7 on 2026-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
