# Generated by Django 6.0.7 on 2026-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_monitoringresult_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringresult',
            name='response_time',
            field=models.FloatField(help_text='Response time in seconds'),
        ),
    ]
